name=AIoT_L501
version=1.0.0
author=AIoT
maintainer=AIoT
sentence=SDK for L501 4G module on Arduino/ESP32.
paragraph=Hỗ trợ các tính năng AT, MQTT, TCP, SMS, Call, Network cho module L501.
category=Communication
url=https://github.com/NW2409/AIoT_L501
architectures=*